import Foundation
import XCTest

final class ConfigurationOverviewLocalizationTests: XCTestCase {
	private static let requiredKeys = [
		"%@ · Editing: %@",
		"%lld automations",
		"%lld button mappings",
		"%lld configured changes",
		"%lld controls · %lld triggers",
		"%lld layers",
		"%lld layer changes",
		"%lld linked apps",
		"%lld steps",
		"%lld stick overrides",
		"%lld wheel actions",
		"1 step",
		"Advanced Triggers",
		"All",
		"and %lld more…",
		"Automatic Activation",
		"Automation Library",
		"Automations",
		"automations",
		"Base",
		"Base stick behavior and tuning",
		"Choose a Control",
		"Choose a control on the visual map, assign what it should do, then save and try it.",
		"Choose what to edit. Runtime layers can activate independently.",
		"Chord · press together",
		"Clear Filters",
		"Clear search",
		"Color follows battery level",
		"Command Wheel",
		"Command wheel action",
		"Configuration Overview",
		"Controller LEDs",
		"Controls",
		"Create or select a profile to view its configuration.",
		"Custom tuning",
		"Disabled in this layer",
		"Dismiss getting started guide",
		"Dismiss this guide",
		"Double tap: %@",
		"Delete “%@”?",
		"EDITING",
		"Edit Layer",
		"Edit Active Layer",
		"Edit mappings on the controller diagram",
		"Editing scope",
		"Filter",
		"Fixed light bar color",
		"hardware settings",
		"Hold for %@",
		"Hold: %@",
		"Inherited",
		"Layer & Hardware",
		"Layer activator",
		"layers",
		"Legacy touchpad region",
		"Legacy touchpad region · %@",
		"Left Stick",
		"LED override",
		"Library",
		"Light bar off",
		"Light bar on",
		"Macro",
		"Runtime layer active now: %@",
		"mapped controls",
		"Missing macro",
		"Missing script",
		"Motion gesture",
		"No Active Profile",
		"No activator assigned",
		"No Mappings Yet",
		"No Matching Configuration",
		"Open %@",
		"Open configuration",
		"Open the visual editor and choose a controller control to create the first mapping.",
		"Open Visual Editor",
		"Other Device Mappings (%lld)",
		"Override",
		"Overrides selected values; the rest inherit from Base",
		"Overrides the Base command wheel",
		"Profile",
		"Repeat: %lld/s",
		"Right Stick",
		"Saved Shared Macro Copy",
		"Script",
		"Search controls, actions, and hints",
		"Sequence · press in order",
		"Settings",
		"Shared Macro",
		"Start with the controller",
		"Toggle %@",
		"Triggers",
		"Try another search or show all configuration types.",
		"This cannot be undone.",
		"This macro is unused. This cannot be undone.",
		"1 place uses this macro. Its macro action will be cleared. This cannot be undone.",
		"%lld places use this macro. Their macro actions will be cleared. This cannot be undone.",
		"This script is unused. This cannot be undone.",
		"1 place uses this script. Its script action will be cleared. This cannot be undone.",
		"%lld places use this script. Their script actions will be cleared. This cannot be undone.",
		"Unnamed Macro",
		"Unnamed Shared Macro",
		"Unused",
		"Hold only: %@",
		"Double tap only: %@",
		"Hold and double tap only",
		"Not available on %@",
		"Unavailable for %@ (%lld)",
		"Overview",
		"D-Pad Preset",
		"Explicitly selected",
		"Derived from individual mappings",
		"Controller Preview",
		"Visual editor layout",
		"Input Latency",
		"Simple key dispatch mode",
		"Profile Auto-Switch",
		"Controller Auto-Switch",
		"%lld linked controllers",
		"Touchpad Input",
		"Active touchpad control set",
		"Legacy Touchpad Modes",
		"%lld saved regions",
		"Pending profile migration",
		"On-Screen Keyboard",
		"Profile-owned",
		"Inherited from another profile",
		"%lld quick texts · %lld apps · %lld websites",
		"%lld tuned values · the rest inherit from Base",
		"Sensitivity %.0f%% · acceleration %.0f%% · deadzone %.0f%%",
		"%@ directions · deadzone %.0f%%",
		"battery color",
		"%@ · %@ · player LEDs %lld · mute %@",
		"Saved Profile Copies",
		"%lld saved steps · missing from shared library",
		"Read-only fallback",
		"These copies keep assigned shared macros working when the original library item is unavailable.",
		"Custom",
		"Active Controller",
		"Standard",
		"Realtime",
		"Whole Pad",
		"Quadrants",
		"Bright",
		"Dim",
		"Breathing",
		"4 Directions",
		"8 Directions",
		"No Advanced Triggers Yet",
		"Create a chord, sequence, or motion gesture in its editor.",
		"Open Chords",
		"No Wheel Actions Yet",
		"Add the first action in Command Wheel settings.",
		"Open Command Wheel",
		"No Hardware Settings Available",
		"Review input settings for the current controller.",
		"Open Input Settings",
		"No Automations Yet",
		"Create a macro or script, then assign it to a control.",
		"Open Macros",
		"Layer LEDs",
		"Map",
		"Automate",
		"Hardware",
		"Activity",
		"Focus Mode",
		"%.0f%% cursor speed",
		"%@ activation · haptics %@",
		"on",
		"off",
		"Analog Trigger Precision",
		"Minimum %.0f%% · deadzone %.0f%% · curve %.0f%%",
		"Pointer-Lock Aiming",
		"Relative mouse behavior for captured-cursor games",
		"Scroll Boost",
		"%.1f× speed",
		"Right-stick double-tap scroll multiplier",
		"Touchpad Cursor & Gestures",
		"Cursor off",
		"Cursor on",
		"Sensitivity %.0f%% · pan %.0f%% · smoothing %.0f%%",
		"Motion Gesture Tuning",
		"%.0f%% sensitivity",
		"%.2f s cooldown",
		"Gyro Aiming",
		"Enabled",
		"Disabled",
		"%@ · sensitivity %.0f%% · deadzone %.0f%%",
		"Oura Motion",
		"Clickpad Edge Input",
		"No modifier",
		"Tilt Back",
		"Tilt Forward",
		"Steer Left",
		"Steer Right",
		"Top Left",
		"Top Right",
		"Bottom Left",
		"Bottom Right",
		"Touch",
		"Click",
		"Both",
		"%@ · Override",
		"%@ · Inherited from Base",
		"Use Base",
		"Remove this layer's LED override",
		"Runtime: %@ · Editing: %@",
		"Edit the layer currently controlling input",
		"Overridden by layer %@",
		"Duplicate layer activator",
		"Player and mute LEDs unavailable on DualShock 4",
		"Player and mute LEDs unavailable over Bluetooth",
		"Layer LED Override",
		"Selecting a color enables the light bar and turns off battery color.",
		"Turning this off removes all LED settings for this layer.",
		"DualShock 4 supports light bar color and brightness. Player and mute LEDs are DualSense features.",
		"Over Bluetooth, player and mute LEDs are unavailable. Light bar color and brightness remain supported.",
		"Used in %lld places",
		"Used in 1 place",
		"Wheel",
		"Wheel Slot %lld",
		"wheel actions",
		"wheel disabled",
		"advanced triggers",
	]

	func testConfigurationOverviewKeysExistWithMatchingPlaceholders() throws {
		let testBundle = Bundle(for: Self.self)
		let appBundleURL = testBundle.bundleURL
			.deletingLastPathComponent()
			.deletingLastPathComponent()
			.deletingLastPathComponent()
		let appBundle = try XCTUnwrap(
			Bundle(url: appBundleURL),
			"Missing host app bundle at \(appBundleURL.path)"
		)

		for localization in ["de", "ja", "zh-Hans", "zh-Hant"] {
			let lprojPath = try XCTUnwrap(
				appBundle.path(forResource: localization, ofType: "lproj"),
				"Missing \(localization) localization bundle"
			)
			let localizedBundle = try XCTUnwrap(Bundle(path: lprojPath))
			let stringsURL = try XCTUnwrap(
				localizedBundle.url(forResource: "Localizable", withExtension: "strings"),
				"Missing Localizable.strings for \(localization)"
			)
			let data = try Data(contentsOf: stringsURL)
			let strings = try XCTUnwrap(
				PropertyListSerialization.propertyList(from: data, format: nil) as? [String: String]
			)

			for key in Self.requiredKeys {
				let translation = try XCTUnwrap(
					strings[key],
					"\(localization) must contain \"\(key)\""
				)
				XCTAssertFalse(translation.isEmpty, "\(localization) must translate \"\(key)\"")
				XCTAssertEqual(
					placeholders(in: translation),
					placeholders(in: key),
					"\(localization) must preserve placeholders in \"\(key)\""
				)
			}
		}
	}

	private func placeholders(in value: String) -> [String] {
		let expression = try! NSRegularExpression(pattern: #"%(?:\d+\$)?(?:lld|@|\.\d+f)"#)
		let range = NSRange(value.startIndex..., in: value)
		return expression.matches(in: value, range: range).compactMap { match in
			guard let swiftRange = Range(match.range, in: value) else { return nil }
			let placeholder = value[swiftRange]
			if placeholder.hasSuffix("lld") { return "%lld" }
			if placeholder.hasSuffix("f") { return String(placeholder) }
			return "%@"
		}.sorted()
	}
}
